### PR TITLE
Would be nice to see this land and get pushed to npm

### PR DESCRIPTION
**Pull request by andyburke**

### CODE REVIEW

**Comment by normanjoyner** [comment]
@andyburke I will fully review this as soon as possible. Can you remove commit 8518f02ac837a5f731193d228ac6e2a05f2cf625 which changes the permissions on all files? Also remove b7a1f71e106680fce5b4e3a42a847ac74417209f as I will perform the bump prior to uploading, shrinkwrapping and creating a new tag.

**Comment by andyburke** [comment]
@normanjoyner updated

Note that I'm just the proxy here after wanting to support members-filtered, I saw @Michieljoris branch and created this pull request based on it.

**Comment by asbjornenge** [comment]
Would :heart: to see this merged soon too :grin: :+1:

**Comment by andyburke** [comment]
Any word on this?

**Comment by Downchuck** [comment]
@normanjoyner checking in on this patch

**Comment by normanjoyner** [comment]
apologies, I've been away for a while. I can hopefully get this merged this week.

**Comment by Downchuck** [comment]
@normanjoyner README.md on the PR has a blurb at the top mentioning that it's a fork. Otherwise, commits look good to me. I have not tested.

**Comment by Downchuck** [comment]
@normanjoyner Checking in.

**Comment by Downchuck** [comment]
@Michieljoris checking in that you are OK with this patch being applied to the serf-rpc upstream

**Comment by Downchuck** [comment]
An undefined "Seq" issue appears if/when issuing a query stream listener following a call to another command (example,  serf.members() then running  serf.listen("query"...) ).

**Comment by normanjoyner** [comment]
@Downchuck i'm seeing the same issue. going to dive into it further.

**Comment by Downchuck** [comment]
@normanjoyner I think that the response is getting pipelined in message pack:

Apart from the silly console.log prefixes...
"outbound ish" is a command (send), "Seeing values" is a decode in msgpack.js.

```
outbound ish [ { Command: 'handshake', Seq: 0 }, { Version: 1 } ]
Seeing values [ { Error: '', Seq: 0 } ]
Serf-RPC online false
outbound ish [ { Command: 'members', Seq: 1 } ]
outbound ish [ { Command: 'stream', Seq: 2 }, { Type: 'query' } ]
outbound ish [ { Command: 'query', Seq: 3 },
  { Name: 'testing', Payload: 'cool' } ]
Seeing values [ { Error: '', Seq: 1 },
  { Members: [ [Object] ] },
  { Error: '', Seq: 2 },
  { Error: '', Seq: 3 },
  { Error: '', Seq: 2 },
  { Event: 'query',
    ID: 1,
    LTime: 14,
    Name: 'testing',
    Payload: <Buffer 63 6f 6f 6c> } ]
```

msgpack.js is only expecting one stream response at a time:

```
    if(values.length == 1)
        var seq = decoded.value.Seq;
    else
        var seq = _.first(values).Seq
```

At a glance, I don't know how to fix this.

**Comment by normanjoyner** [comment]
@Downchuck I was able to reproduce and fix locally. I'm going to merge this PR into a development branch, add the fixes for the issue you reported and merge it all into master.

**Comment by Downchuck** [comment]
Thank you much @normanjoyner  !

**Comment by normanjoyner** [comment]
It appears that this does not fix the Members scenario however. Since there is no Seq in the response it gets lost in the shuffle. Going to see if I can get that resolved first.

**Comment by normanjoyner** [comment]
@Michieljoris can you merge this into the development branch so I can add additional fixes before merging to master and releasing?

**Comment by normanjoyner** [comment]
Realized I could open another PR against that branch. tracking it here: https://github.com/normanjoyner/serf-rpc/pull/6

**Comment by normanjoyner** [comment]
Merged in #6.

**Comment by normanjoyner** [comment]
pushed to npm: serf-rpc@0.2.1

**Pull request closed without merging**
